CREATE TABLE users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(25) NOT NULL UNIQUE,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    salt BINARY(16) NOT NULL,
    secret BINARY(32) NOT NULL
);

CREATE TABLE message (
    id INT PRIMARY KEY AUTO_INCREMENT,
    userID INT,
    message VARCHAR(25) NOT NULL UNIQUE,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(userID) REFERENCES users(id)
);

UPDATE properties
SET value = '3'
WHERE name = "version";